apiVersion: v1
kind: BuildConfig
metadata:
  name: java-base-layer
spec:
  nodeSelector: 
    type: builder
  output:
    to:
      kind: DockerImage
      name: quay-enterprise-quay-enterprise.apps.andy-e2.casl-contrib.osp.rht-labs.com/admin/java-base-layer:1-1
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.3
        namespace: openshift
    type: Docker
  triggers: []
