apiVersion: v1
kind: Template
metadata:
  name: image-signing-request-template
  annotations:
    openshift.io/display-name: Image Signing Request Template
    description: Template to create an Image Signing Request
objects:
- apiVersion: "imagesigningrequests.cop.redhat.com/v1alpha1"
  kind: ImageSigningRequest
  metadata:
    name: ${IMAGE_SIGNING_REQUEST_NAME}
  spec:
    containerImage:
      kind: ImageStreamTag
      name: "${IMAGE_STREAM_TAG}"
    pullSecret: 
      name: "security-openshift-pull-secret"
parameters:
- name: IMAGE_SIGNING_REQUEST_NAME
  displayName: Image Signing Request Name
  description: Name of the Image Signing Request
  required: true
- description: ImageStream Tag of the Image to Sign (Format is <imagestream>:<tag>)
  displayName: ImageStream Tag
  name: IMAGE_STREAM_TAG
  required: true
